services:
  - type: web
    name: taskmanager
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/taskmanager-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://<your-db-host>:3306/<your-db-name>
      - key: SPRING_DATASOURCE_USERNAME
        value: <your-username>
      - key: SPRING_DATASOURCE_PASSWORD
        value: <your-password>
